SHARED_LIBNAME_GLOBAL = libgrimoire.so
SHARED_LIBVER_MAJOR = 1
SHARED_LIBVER_MINOR = 0.0
SHARED_LIB = $(SHARED_LIBNAME_GLOBAL).$(SHARED_LIBVER_MAJOR)
SHARED_LIBFILE = $(SHARED_LIB).$(SHARED_LIBVER_MINOR)

CFLAGS = -shared -Wl,-soname,$(SHARED_LIB) -o $(SHARED_LIB)
LDFLAGS = -lc -lssl -lcrypt

all :
	$(AR) -x $(OUTPUT_GLOBAL)/grimoire
	$(CC) $(CFLAGS) *.o $(LDFLAGS)
	@echo "install shared library into /usr/lib"
	@sudo rm -f /usr/lib/$(SHARED_LIB)
	@sudo cp $(SHARED_LIB) /usr/lib
	@sudo rm -f /usr/lib/$(SHARED_LIBNAME_GLOBAL)
	@sudo ln -s /usr/lib/$(SHARED_LIB) /usr/lib/$(SHARED_LIBNAME_GLOBAL)

.PHONY : all
